### ISSUE TITLE
Adding a place to learn more about the base and supplementary styles

### ISSUE THREAD

**Issue by mickremedi** [errata-ai/vale.sh#47]
For a beginner, the config generator you lead us to in the ["Quick Start" section](https://vale.sh/docs/vale-cli/structure/#quick-start) is a bit overwhelming since we don't know when to choose one style over another. This is especially true for the base styles since you recommend that we only use one.

Could there be a section that discusses some high level differences between the 3 base styles? Perhaps breaking it down into answering a few questions:

1. Who is the target audience?
2. What is the tone? Is it formal/professional? Or is it more informal/conversational?
3. What is the stance on vocabulary? Does it try to avoid technical jargon?
4. Is there anything unique about this style guide?
5. etc.

Supplementary styles seem to be one-off's? So perhaps guiding us to where we can learn more about these supplementary styles?

**Comment by jdkato** [comment]
Browsing the [Package Hub](https://vale.sh/hub/) is a good place to start. Each package links to its Vale implementation and the reference style guide. The latter of which should answer most of your questions.

Also note that the reference style guides are are written and maintained by third parties, independent of any Vale-related details. So I would argue that Vale's docs are not the place to become familiar with them.

> This is especially true for the base styles since you recommend that we only use one.

I recommend this because it's not uncommon for these styles to recommend conflicting advice (heading capitalization style, for example).
